### ISSUE TITLE
FSK modem support

### ISSUE THREAD

**Issue by juliantech5** [jgromes/LoRaLib#34] opened 2018-08-13 12:39 UTC
Would it be possible to receive FSK packets with this library?

**Comment by jgromes** [comment] 2018-08-13 12:44
FSK modem support is not currently implemented. LoRaLib only supports the LoRa modem (as the name suggests).

Is there a reason why you want to use FSK specifically on SX127x chips? You could use RFM69 chips with [KiteLib](https://github.com/jgromes/KiteLib) for FSK, and you could use the same public interface as LoRaLib.

**Comment by juliantech5** [comment] 2018-08-13 12:45
We are currently developing a satellite with a LoRa downlink using the sx1278, we require an FSK uplink due to regulations though.

**Comment by jgromes** [comment] 2018-08-13 12:47
And I suppose you don't want to have SX1278 only for downlink and RFM69 only for uplink?

**Comment by juliantech5** [comment] 2018-08-13 12:49
Yeah exactly, we can implement it but we already have a near complete prototype

**Comment by jgromes** [comment] 2018-08-13 12:53
I will investigate a bit. Can't promise anything though.

**Comment by juliantech5** [comment] 2018-08-13 13:07
Do you have an email address or other means of contact?

**Comment by jgromes** [comment] 2018-08-13 13:10
Sorry, I'd rather keep all GitHub-related communication here.

**Comment by juliantech5** [comment] 2018-08-13 13:11
Sure

**Comment by Bambofy** [comment] 2018-08-13 15:35
Hi, allow the modem mode to be switched between FSK and LoRa at runtime please!

**Comment by jgromes** [comment] 2018-08-13 15:36
I'm counting on that, this was obvious from the single-chip requirement. It will require substantial changes to the public API though.

**Comment by jgromes** [comment] 2018-08-13 18:01
I made a new branch [fsk-modem](https://github.com/jgromes/LoRaLib/tree/fsk-modem), all the development will be there until everything is tested properly.

There will be a lot of changes, both in public API and in the backend, so it will take me a few weeks to implement the support.

**Comment by juliantech5** [comment] 2018-08-13 18:43
Thanks jgromes, really appreciated :) Please keep us updated!

**Comment by jgromes** [comment] 2018-08-14 04:32
First draft of the API:

Call `beginFSK();` to start the FSK modem and disable LoRa modem. Similarly, calling `begin()` will start LoRa modem and disable FSK. All calls to methods like `transmit()`, `receive()` etc. will be routed through the currently active modem.

What do you guys think about this?

**Comment by Bambofy** [comment] 2018-08-14 08:29
Yep sounds perfect.

**Comment by jgromes** [comment] 2018-08-15 09:09
Basic FSK transmission is in 736f709a505c6cb1960f4be0377446fc43dffbff, currently only for SX1278. On SDR receiver it seems to be transmitting, although that will have to be tested with receiving SX1278.

What do you need in terms of the features? Do you need interrupt-driven Tx and Rx as well as the default blocking ones?

What about configuration? Currently you can set bit rate, receiver bandwidth, frequency deviation and all the settings that aren't exclusive to LoRa (gain, overcurrent protection etc.). But there are other FSK settings, e.g. modulation shaping. Currently it's left to the default Gaussian filter with BT=0.3. Do you need access to that in the public API as well?

**Comment by juliantech5** [comment] 2018-08-15 11:17
Thanks for your quick work jgromes! I'll test it out now on the satellite and let you know, In theory, we should be fine with the current settings but it would be great to have the option to change modulation shaping and other settings in the Public API.

I don't think FSK uses address filtering like LoRa does, we don't personally need it but it may come in useful. 

Thanks again!

**Comment by Bambofy** [comment] 2018-08-15 12:48
Hi James, ISR functions aren't needed (bit skeptical, simpler the better) also the configuration is great we don't need to change anything else. Is there a chance you can add timeouts to the receive and transmit functions? and how does the receive and transmit function handle timing out at the moment?

Cheers

**Comment by jgromes** [comment] 2018-08-15 12:55
Right now timeouts are set to 150% of expected transmission time based on the bit rate and payload size. Receive function isn't implemented yet, I'm working on that right now.

**Comment by Bambofy** [comment] 2018-08-15 12:57
Thanks, awesome library, thanks for making it. will credit you in our project FOSSASAT-1 (http://fossa.systems)

**Comment by jgromes** [comment] 2018-08-15 14:18
Basic FSK reception is implemented in f903e2908f26497f7eab1bc3fceca5ae2e05955f, so all the basic FSK methods are done for SX1278. Next up is finishing configuration, examples and code cleanup.

Side note: The crystals on the cheap SX1278 modules are pretty bad, even at room temperature the carrier frequency is 6-8 kHz off. LoRa can receive packets that are off by less than 25% of bandwidth, and that gets pretty narrow for the lower bandwidth values (which you need in order to maximize distance). How do you plan on adddressing that?

**Comment by juliantech5** [comment] 2018-08-15 14:26
We are trying to use the highest bandwidth possible as allowed by the IARU
and the ITU, due to these duty cycle limitations we have integrated a
tuning packet system that sends high bandwidth packets every set amount of
time. We will need to account for this on the ground station and are also
looking at sourcing or developing our own SX1278 modules with low tolerance
crystals. Stuart integrated AFC tuning packets on his Lora tracker library
at the beginning of each sketch, would that be something that you could
integrate?

Thanks

**Comment by jgromes** [comment] 2018-08-15 14:29
So you want to add some form of automatic frequency calibration?

**Comment by juliantech5** [comment] 2018-08-15 14:35
Yes Indeed, right now we sort of have a working version that changes the ground station centre freq when it hears the satellite using the freq offset.

**Comment by juliantech5** [comment] 2018-08-15 14:37
We are doing testing in low temperatures though and it seems like it will work regardless, the drift is not immense. A TCXO would be ideal though just to be safe.

**Comment by jgromes** [comment] 2018-08-15 14:38
See #26 

Basically, I don't want to add it into the API, because LoRaLib is intended only as a control interface for SX127x series. Anything above what the chip itself can do is out of scope in my opinion.

**Comment by juliantech5** [comment] 2018-08-15 14:41
Yeah of course, No problem. I'll test out the FSK now, are the settings supposed to be working btw?

**Comment by jgromes** [comment] 2018-08-15 14:44
Basic settings like carrier frequency, bit rate, receiver bandwidth, frequency deviation and sync word should be working. Output power and over current protection should work too (because they are not dependent on modulation type).

**Comment by juliantech5** [comment] 2018-08-15 14:52
Great, Seems to be working perfectly. Thank you for the help! FSK functionality is not needed when you have LoRa but due to current ITU regulations, we need to have a backup modulation in case LoRa does not work for emergency procedures during orbit.

**Comment by jgromes** [comment] 2018-08-16 07:44
The most important functions of FSK modem are now implemented. The current support for FSK modem on SX127x chips in LoRaLib is now the same as on RF69 chips in KiteLib.

I will be doing a bit of testing, and in case no major bugs are found within a few days, I will merge fsk-modem branch into master. If you find any bugs on your end, please report them in a separate issue. Thanks!

**Comment by Bambofy** [comment] 2018-08-16 10:05
Thank you for implement it :) do you have any idea on the power consumption of switching modem modes?

**Comment by jgromes** [comment] 2018-08-16 10:42
The modem change itself is just an SPI write to a single register while the module is in sleep mode. Then, configuration is performed, which is done in standby mode and takes just a few milliseconds. I don't think power consumption will be particularly increased when switching from LoRa mode to FSK or vice-versa. Haven't measured it though.

**Comment by Bambofy** [comment] 2018-08-16 18:38
alright so i assume we would be alright to switch between FSK and LoRa every loop? thanks, can i contact you for advise through email?

**Comment by jgromes** [comment] 2018-08-16 18:51
It should be fine. You can also put the module into sleep mode by calling `sleep()` to minimize current draw down to just a few uA. The module will wake up automatically when you try to transmit or attempt to receive.

Sorry, I'd rather keep all GitHub-related communication here. If you have any questions in the future, feel free to open a new issue.

**Comment by jgromes** [comment] 2018-08-17 11:13
@Bambofy 
> Additionally, on the receiving arduino program, will it be able to listen to both FSK and LoRa transmission at the same time, or will we have to switch that receiver modem too? if we have to switch the receiver modem that will make the timing of everything very difficult?

There's no way to achieve that on SX127x, because only one of the modems can be active at any given given time.

**Comment by juliantech5** [comment] 2018-08-17 12:16
Slightly off-topic to FSK,
Do you know how we could use transmit FM tones using the sx1278? (say morse for example)

Thanks

**Comment by jgromes** [comment] 2018-08-17 12:46
I don't think you can. SX1278 has something called "continuous mode", in which it transmits anything that is read on DIO1 (clock) and DIO2 (data) pins. It _might_ be possible to use this to generate FM tones, but I really don't know enough about FM and FSK modulations to tell you for sure. Continuous mode isn't implemented and I'm not planning on adding it.

Besides, the module was designed for digital data transmission - not analog FM tones.

**Comment by juliantech5** [comment] 2018-08-17 12:48
Ah ok No problem was just wondering. 
And with the current state of the FSK modem would it be possible to transmit FSK RTTY with some modifications?

**Comment by jgromes** [comment] 2018-08-17 12:57
I'm not sure about that: how fast can RTTY signals be? The lowest possible bit rate of the module is 1.2 kbps, I think that is way too fast.

**Comment by juliantech5** [comment] 2018-08-17 13:27
Stuart has a library that transmits RTTY FSK using Lo-Ra, https://github.com/LoRaTracker/LoRaTracker-Library
Would this be hard to integrate into this library?

**Comment by jgromes** [comment] 2018-08-17 13:44
Seems to be using the aforementioned continuous mode.

No idea, since I don't have any experience with RTTY. I would suggest contacting the author of that library.

**Comment by Bambofy** [comment] 2018-08-18 09:30
Hi, doesn't the SX1278 transmit analog FSK modulated signals?

If yes then shouldn't a RTTY terminal process the FSK transmissions anyway?

**Comment by jgromes** [comment] 2018-08-18 09:58
I don't know how exactly are the data encoded in the FSK output of SX1278, but it's not just plain binary FSK (high frequency = 1; low frequency = 0). If that was the case then yes, you could receive it with RTTY terminal (provided you manage to get the timings right).

**Comment by jgromes** [comment] 2018-08-18 13:43
Since all the bugs I found during testing were resolved, I merged the fsk-modem branch into master.
LoRaLib now has FSK support in release 5.1.0

Feel free to open new issues for bugs/change requests.

**Closed by jgromes** 2018-08-18 13:43 UTC
Labels: enhancement

**Comment by jgromes** [comment] 2018-08-18 18:52
@juliantech5 @Bambofy since you guys asked for it ... https://www.youtube.com/watch?v=a0CyXdC6qJg :smile:

**Comment by juliantech5** [comment] 2018-08-18 18:57
Please give this man an award, your name will be in space my friend.

**Comment by retzbeats** [comment] 2019-10-30 21:04
Hi jgromes! we are actually using the sx1278 for 433MHz FSK with RadioLib, but we need the signal strength information, we have already check the register map for FSK in the sx1278 and RSSI value is available. Do you have a function to read this in the receiver? or can you make that available?

**Comment by jgromes** [comment] 2019-10-30 21:22
@retzbeats you're replying to an issue that was resolved well over a year ago. Please open a new issue either in RadioLib or here.

**Comment by retzbeats** [comment] 2019-10-31 13:04
> @retzbeats you're replying to an issue that was resolved well over a year ago. Please open a new issue either in RadioLib or here.

Sorry, you are right. I have opened the issue in RadioLib thanks
