### ISSUE TITLE
lora

### ISSUE THREAD

**Issue by bakhshizadeh** [jgromes/LoRaLib#48] opened 2018-10-20 11:06 UTC
please help me.how can i transmit data after receive data in receiveIntterupt.ino

**Comment by jgromes** [comment] 2018-10-20 11:10
Have you tried `lora.transmit()`? Seems rather obvious to me.

**Comment by bakhshizadeh** [comment] 2018-10-20 11:13
yes

**Comment by jgromes** [comment] 2018-10-20 11:15
And? Was there an error code? Did it not transmit? I need more information in order to help you.

**Comment by bakhshizadeh** [comment] 2018-10-20 11:17
/*
   LoRaLib Receive with Inerrupts Example
   This example listens for LoRa transmissions and tries to
   receive them. Once a packet is received, an interrupt is
   triggered. To successfully receive data, the following
   settings have to be the same on both transmitter 
   and receiver:
    - carrier frequency
    - bandwidth
    - spreading factor
    - coding rate
    - sync word
    - preamble length
   For more detailed information, see the LoRaLib Wiki
   https://github.com/jgromes/LoRaLib/wiki
*/

// include the library
#include <LoRaLib.h>
#include <avr/sleep.h>

int wakePin = 3;                 // pin used for waking up

void wakeUpNow()        // here the interrupt is handled after wakeup
{
  // execute code here after wake-up before returning to the loop() function
  // timers and code using timers (serial.print and more...) will not work here.
  // we don't really need to execute any special functions here, since we
  // just want the thing to wake up
}

// create instance of LoRa class using SX1278 module
// this pinout corresponds to LoRenz shield: 
// https://github.com/jgromes/LoRenz
// NSS pin:   7 (18 on ESP32 boards)
// DIO0 pin:  2
// DIO1 pin:  3
// IMPORTANT: because this example uses external interrupts,
//            DIO0 MUST be connected to Arduino pin 2 or 3.
//            DIO1 MAY be connected to any free pin 
//            or left floating.
SX1278 lora = new LoRa;

void setup() {
  pinMode(wakePin,INPUT);
  Serial.begin(9600);

  // initialize SX1278 with default settings
  Serial.print(F("Initializing ... "));
  // carrier frequency:           433.0 MHz
  // bandwidth:                   125.0 kHz
  // spreading factor:            9
  // coding rate:                 7
  // sync word:                   0x12
  // output power:                17 dBm
  // current limit:               100 mA
  // preamble length:             8 symbols
  // amplifier gain:              0 (automatic gain control)
  int state = lora.begin();
  lora.setFrequency(433.0);
  if (state == ERR_NONE) {
    Serial.println(F("success!"));
  } else {
    Serial.print(F("failed, code "));
    Serial.println(state);
    while (true);
  }

  // set the function that will be called 
  // when new packet is received
  lora.setDio0Action(setFlag);
  
  // start listening for LoRa packets
  Serial.print(F("Starting to listen ... "));
  state = lora.startReceive();
  if (state == ERR_NONE) {
    Serial.println(F("success!"));
  } else {
    Serial.print(F("failed, code "));
    Serial.println(state);
    while (true);
  }

  // if needed, 'listen' mode can be disabled by calling
  // any of the following methods:
  //
  //lora.standby();
  // lora.sleep();
  // lora.transmit();
  // lora.receive();
  // lora.scanChannel();

  attachInterrupt(1, wakeUpNow, RISING); // use interrupt 0 (pin 2) and run function
                                         // wakeUpNow when pin 2 gets RISING
}

// flag to indicate that a packet was received
volatile bool receivedFlag = false;

// disable interrupt when it's not needed
volatile bool enableInterrupt = true;

// this function is called when a complete packet
// is received by the module
// IMPORTANT: this function MUST be 'void' type
//            and MUST NOT have any arguments!
void setFlag(void) {
  // check if the interrupt is enabled
  if(!enableInterrupt) {
    return;
  }

  // we got a packet, set the flag
  receivedFlag = true;
}

void sleepNow()         // here we put the arduino to sleep
{
    /* Now is the time to set the sleep mode. In the Atmega8 datasheet
     * http://www.atmel.com/dyn/resources/prod_documents/doc2486.pdf on page 35
     * there is a list of sleep modes which explains which clocks and
     * wake up sources are available in which sleep mode.
     *
     * In the avr/sleep.h file, the call names of these sleep modes are to be found:
     *
     * The 5 different modes are:
     *     SLEEP_MODE_IDLE         -the least power savings
     *     SLEEP_MODE_ADC
     *     SLEEP_MODE_PWR_SAVE
     *     SLEEP_MODE_STANDBY
     *     SLEEP_MODE_PWR_DOWN     -the most power savings
     *
     * For now, we want as much power savings as possible, so we
     * choose the according
     * sleep mode: SLEEP_MODE_PWR_DOWN
     *
     */  
    set_sleep_mode(SLEEP_MODE_PWR_DOWN);   // sleep mode is set here
 
    sleep_enable();          // enables the sleep bit in the mcucr register
                             // so sleep is possible. just a safety pin
 
    /* Now it is time to enable an interrupt. We do it here so an
     * accidentally pushed interrupt button doesn't interrupt
     * our running program. if you want to be able to run
     * interrupt code besides the sleep function, place it in
     * setup() for example.
     *
     * In the function call attachInterrupt(A, B, C)
     * A   can be either 0 or 1 for interrupts on pin 2 or 3.  
     *
     * B   Name of a function you want to execute at interrupt for A.
     *
     * C   Trigger mode of the interrupt pin. can be:
     *             LOW        a low level triggers
     *             CHANGE     a change in level triggers
     *             RISING     a rising edge of a level triggers
     *             FALLING    a falling edge of a level triggers
     *
     * In all but the IDLE sleep modes only LOW can be used.
     */
 
    attachInterrupt(1,wakeUpNow, RISING); // use interrupt 0 (pin 2) and run function
                                       // wakeUpNow when pin 2 gets LOW
 
    sleep_mode();            // here the device is actually put to sleep!!
                             // THE PROGRAM CONTINUES FROM HERE AFTER WAKING UP
 
    sleep_disable();         // first thing after waking from sleep:
                             // disable sleep...
    detachInterrupt(1);      // disables interrupt 0 on pin 2 so the
                             // wakeUpNow code will not be executed
                             // during normal running time.
 
}

void loop() {
  int state1 = lora.startReceive();
  if (state1 == ERR_NONE) {
    Serial.println(F("success!"));
  } else {
    Serial.print(F("failed, code "));
    Serial.println(state1);
    //while (true);
  }
 // lora.startReceive();
  if (!receivedFlag){
    Serial.println("sleep11111111111111111111111111111111111");
    delay(100);
   sleepNow(); 
   delay(100);
   Serial.println("sleep222222222222222222222222222222222222");
  }// sleep function called here
  if(receivedFlag) {
    // disable the interrupt service routine while
    // processing the data
    enableInterrupt = false;

    // reset flag
    receivedFlag = false;
    
    // you can read received data as an Arduino String
    String str;
    int state = lora.readData(str);
  
    // you can also read received data as byte array
    /*
      byte byteArr[8];
      int state = lora.receive(byteArr, 8);
    */
    
    if (state == ERR_NONE) {
      // packet was successfully received
      Serial.println("Received packet!");
  
      // print data of the packet
      Serial.print("Data:\t\t\t");
      Serial.println(str);
  
      // print RSSI (Received Signal Strength Indicator) 
      Serial.print("RSSI:\t\t\t");
      Serial.print(lora.lastPacketRSSI);
      Serial.println(" dBm");
  
      // print SNR (Signal-to-Noise Ratio) 
      Serial.print("SNR:\t\t\t");
      Serial.print(lora.lastPacketSNR);
      Serial.println(" dBm");

      // print frequency error
      Serial.print("Frequency error:\t");
      Serial.print(lora.getFrequencyError());
      Serial.println(" Hz");
  
    } else if (state == ERR_CRC_MISMATCH) {
      // packet was received, but is malformed
      Serial.println("CRC error!");
  
    }
    // we're ready to receive more packets,
    // enable interrupt service routine
    enableInterrupt = true;
   // delay(2000);
    state = lora.startTransmit("Mahmood"); 
    if (state =! ERR_NONE){
      Serial.print(F("failed, code = "));
      Serial.println(state);
    }
    //delay(2000);
  }

}

**Comment by bakhshizadeh** [comment] 2018-10-20 11:19
in below code state variable show 1
Serial.print(F("failed, code = "));
Serial.println(state);

**Comment by bakhshizadeh** [comment] 2018-10-20 11:30
i use lora.transmit() but i have the same problem.

**Comment by bakhshizadeh** [comment] 2018-10-20 11:37
if Error codes be negative, that works correct?

**Comment by jgromes** [comment] 2018-10-20 11:39
https://github.com/jgromes/LoRaLib/wiki/Error-Codes

**Comment by bakhshizadeh** [comment] 2018-10-20 11:46
may you send me a transiver code with lora?please

**Comment by jgromes** [comment] 2018-10-20 12:18
Sorry, but this is not how GitHub issues work. This is a place you go to if you have found a bug in the library, or if you want to suggest new features. For help with Arduino code in general, go to Arduino formus.

I was unable to reproduce your problem, which leads me to believe it is not a bug in the library code. That means I have to close this issue now.

Few pointers to help you:
1. Don't try to do everything at the same time. Start with code that can transmit after reception. Only add new features after you're confident that is working.
2. Read the examples and the [wiki](https://github.com/jgromes/LoRaLib/wiki). One of the comments in ReceiveInterrupt says that listen mode will be disabled by calling - among other things - `lora.transmit()`. Do you re-enable the listen mode?

**Comment by bakhshizadeh** [comment] 2018-10-20 12:44
i think so.i download LoRalib-master folder today. do i re-enable it?

**Comment by bakhshizadeh** [comment] 2018-10-27 10:32
hi.excuse me.i transmit data and receiver side receive data but i have error code -16 in transmit side.may you help me?i know error -16 is faulty spi wiring. 
    On Saturday, October 20, 2018, 3:48:19 PM GMT+3:30, Jan Gromeš <notifications@github.com> wrote:  
 
 
Sorry, but this is not how GitHub issues work. This is a place you go to if you have found a bug in the library, or if you want to suggest new features. For help with Arduino code in general, go to Arduino formus.

I was unable to reproduce your problem, which leads me to believe it is not a bug in the library code. That means I have to close this issue now.

Few pointers to help you:
   
   - Don't try to do everything at the same time. Start with code that can transmit after reception. Only add new features after you're confident that is working.
   - Read the examples and the wiki. One of the comments in ReceiveInterrupt says that listen mode will be disabled by calling - among other things - lora.transmit(). Do you re-enable the listen mode?

**Comment by bakhshizadeh** [comment] 2018-10-27 13:15
can you help me that where is my problem?address   0x1bits    2  0value   0b11current 0b10001001mask 0b111new 0b10001011read 0b0
    On Saturday, October 27, 2018, 3:57:45 PM GMT+3:30, Jan Gromeš <notifications@github.com> wrote:  
 
 
Code -16 means that expected value in some SPI register did not match expected value after writing. This can be caused by too long SPI wires, or general isntability of the system. You can get additional information (such as which register failed) by running LoRaLib in debug mode (uncomment this line in TypeDef.h and re-upload sketch).

**Comment by jgromes** [comment] 2018-10-27 13:36
This error occured when switching the LoRa module from standby mode to transmit mode. For some reason, the value read after writing was 0b00000000 instead of the expected 0b10001011. Value 0b00000000 seems very suspicious - it looks like the chip stopped responding to SPI read commands. In any case this is most likely hardware related: too long wires, strong EM noise from the background or power supply issues.

One workaround I can think of is increasing delay between SPI write and the vrite verification. Go to [this line](https://github.com/jgromes/LoRaLib/blob/032bd60184f55b4b7c0eaa57e092935257c7ecdc/src/Module.cpp#L63) in Module.cpp and change the delay to 10 ms.

**Comment by bakhshizadeh** [comment] 2018-10-27 14:11
is my hardware correct in attached photo?
    On Saturday, October 27, 2018, 5:06:08 PM GMT+3:30, Jan Gromeš <notifications@github.com> wrote:  
 
 
This error occured when switching the LoRa module from standby mode to transmit mode. For some reason, the value read after writing was 0b00000000 instead of the expected 0b10001011. Value 0b00000000 seems very suspicious - it looks like the chip stopped responding to SPI read commands. In any case this is most likely hardware related: too long wires, strong EM noise from the background or power supply issues.

One workaround I can think of is increasing delay between SPI write and the vrite verification. Go to this line in Module.cpp and change the delay to 10 ms.

**Comment by jgromes** [comment] 2018-10-27 14:16
Please reply on GitHub, not to the email ...

**Comment by jgromes** [comment] 2018-10-27 14:35
What exactly am I supposed to tell from that photo? None of the pins on the LoRa module are labeled, and thanks to that flash I can't even tell which wire goes where.

With that in mind, you are probably using module with 3,3 V logic on 5 V Arduino. It might be (kind of) working now, but eventually, it will start smoking.

**Comment by jgromes** [comment] 2018-10-27 14:38
Also, none of this has any relation to the library. Go to Arduino forums to get help with Arduino in general.

**Closed by jgromes** 2018-10-27 14:38 UTC

**Comment by bakhshizadeh** [comment] 2018-10-28 12:42
hi.can you help me that how connect arduino uno r3 board to sx1278 in lora mode?

**Comment by jgromes** [comment] 2018-10-28 13:55
From my previous comment:
> Go to Arduino forums to get help with Arduino in general.

**Comment by bakhshizadeh** [comment] 2018-11-19 19:35
Hi.excuse me.may you help me? i receive data in interruptreceive and send data to other lora up to 4 character very well. But when i want to send 5 or more character it doesnot work well.

**Comment by bakhshizadeh** [comment] 2018-12-23 11:37
hi.excuse me.how to put lora sx1278 in standby or sleep mode and listen mode? i want to decrease power consumption.

**Comment by jgromes** [comment] 2018-12-29 18:10
Once again, this has nothing to do with the library.

From [SX1278 datasheet](https://www.semtech.com/uploads/documents/DS_SX1276-7-8-9_W_APP_V5.pdf), page 14, supply current in receive mode will always be 11 - 12 mA. You can decrease the overall power consumption by putting the module to sleep mode when you don't need it.

Locking as off-topic.
