### ISSUE TITLE
SX1268 Support

### ISSUE THREAD

**Issue by juliantech5** [jgromes/LoRaLib#53] opened 2018-12-13 22:24 UTC
Is the SX1268 Supported? I am assuming it works in the same way as an SX1278 but still doesn't have the modules for testing?

Cheers.
Julian

**Comment by jgromes** [comment] 2018-12-14 08:32
Duplicate of #28.

Looking at the datasheet, it looks like the SPI interface is quite different from SX1278, so it most likely won't work out-of-the-box.

Is there any reason why should SX1268 be supported? Most people will be using SX127x series anyway, since there are so many cheap modules out there.

**Closed by jgromes** 2018-12-14 08:32 UTC
Labels: duplicate

**Comment by juliantech5** [comment] 2018-12-14 13:52
Ah ok, a couple of HAB and GPS trackers are using the sx1262 with E22 modules, there are no Arduino libraries for that.

Indeed sx127x are more common though.

**Comment by juliantech5** [comment] 2019-03-31 14:48
Hey Jgromes, there seems to be a recent increase in the SX1262 units on the market due to their higher efficiency and overall performance. Are you considering integrating this chip into the library? The only RF module that uses a TCXO temperature controlled crystal is the SX1262 and it happens to be essential for satellite operation in varying temperatures. I can send you some units for development if you are interested. 

Thanks,
Julian

**Comment by jgromes** [comment] 2019-03-31 15:44
Hi Julian,

From briefly reading through the datasheet, it looks like the SPI interface was heavily modified. I will have a go at it, but it will have to be in RadioLib, not here. You can get in touch on gromes.jan@gmail.com, we can discuss details there.

**Comment by jgromes** [comment] 2019-04-04 08:43
So after reading the datasheet a bit more, it looks like they completely removed FSK direct mode. Unfortunately, that's at the core of the hack I used to get these modules to transmit RTTY. I assume that's a bit of a deal breaker for you?

**Comment by addaedans** [comment] 2019-04-07 19:36
Hi! Well that sound nice. I was recently bought a few of these and did not believe that there is still no library that supports these superior chips...I am not an expert in C++ at all but i found C++ implementation of arduino examples using simple ping-pong comm. If you are interested in it i can search for the link. It is hidden on the Dorji website and i think have all the basic s to start out. Thanks for the work on the library by the way. it works nicely.

**Comment by jgromes** [comment] 2019-04-08 05:10
@addaedans could you post the links to the example to https://github.com/jgromes/RadioLib/issues/9? Thanks

**Comment by juliantech5** [comment] 2019-04-08 12:14
Hey Jgromes,

Indeed RTTY is needed for our application since we already requested its use to the IARU, worst case we could have an SX1278 for RTTY and an SX1262 for LoRa. It would be really great if we could get it to work all on the SX1262.  I have a couple of chips around and can ship you one if you need it for testing, either way they seem to be popping up all over the place. Thanks a lot for your help, really appreciated.

**Comment by jgromes** [comment] 2019-04-08 12:54
I ordered some, but it will take about a month to arrive. There's a separate issue for SX126x support in RadioLib (https://github.com/jgromes/RadioLib/issues/9), all the progres updates will be there.
